-- YUKCEP DB SCHEMA (Supabase / Postgres)
-- This schema matches the current frontend contract in src/App.jsx and src/components/AuthScreen.jsx.

-- USERS (Supabase Auth ile senkronize)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  phone TEXT,
  role TEXT NOT NULL DEFAULT 'driver' CHECK (role IN ('driver', 'employer', 'admin')),
  rating NUMERIC(2,1) DEFAULT 5.0 CHECK (rating >= 0 AND rating <= 5),
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- LOADS (Yuk Ilanlari)
CREATE TABLE IF NOT EXISTS public.loads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  origin_city TEXT NOT NULL,
  destination_city TEXT NOT NULL,
  distance_km INTEGER,
  load_type TEXT NOT NULL,
  trailer_type TEXT CHECK (trailer_type IN ('Kapalı', 'Açık', 'Frigorifik', 'Damperli')),
  weight_kg INTEGER,
  price NUMERIC(12,2),
  currency TEXT NOT NULL DEFAULT 'TRY',
  kdv_included BOOLEAN NOT NULL DEFAULT true,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'assigned', 'in_transit', 'delivered', 'completed', 'cancelled')),
  pickup_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  is_urgent BOOLEAN NOT NULL DEFAULT false,
  is_fleet BOOLEAN NOT NULL DEFAULT false,
  truck_count INTEGER NOT NULL DEFAULT 1 CHECK (truck_count > 0)
);

-- BIDS (Teklifler)
CREATE TABLE IF NOT EXISTS public.bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id BIGINT NOT NULL REFERENCES public.loads(id) ON DELETE CASCADE,
  driver_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE(load_id, driver_id)
);

-- NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id UUID NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- RUNTIME LOGS (istemci hata/olay izleme)
CREATE TABLE IF NOT EXISTS public.runtime_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_event_at TIMESTAMPTZ,
  level TEXT NOT NULL CHECK (level IN ('info', 'warn', 'error')),
  event_code TEXT NOT NULL,
  details TEXT,
  session_id TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  screen TEXT,
  app_version TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- MODERATION / ABUSE REPORTS
CREATE TABLE IF NOT EXISTS public.abuse_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id BIGINT REFERENCES public.loads(id) ON DELETE CASCADE,
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (char_length(reason) >= 6),
  details TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- PUBLIC FEEDBACK BOARD
CREATE TABLE IF NOT EXISTS public.feedback_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  content TEXT NOT NULL CHECK (char_length(content) >= 6),
  codex_comment TEXT NOT NULL,
  status_tag TEXT NOT NULL DEFAULT 'yapilacak' CHECK (status_tag IN ('yapildi', 'yapilacak', 'kotu_fikir')),
  moderation_status TEXT NOT NULL DEFAULT 'published' CHECK (moderation_status IN ('published', 'filtered')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Compatibility alters for existing deployments (safe to re-run)
ALTER TABLE IF EXISTS public.profiles
  ADD COLUMN IF NOT EXISTS phone TEXT;

ALTER TABLE IF EXISTS public.profiles
  ADD COLUMN IF NOT EXISTS rating NUMERIC(2,1) DEFAULT 5.0 CHECK (rating >= 0 AND rating <= 5);

ALTER TABLE IF EXISTS public.loads
  ADD COLUMN IF NOT EXISTS kdv_included BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE IF EXISTS public.bids
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now());

ALTER TABLE IF EXISTS public.loads
  DROP CONSTRAINT IF EXISTS loads_status_check;

ALTER TABLE IF EXISTS public.loads
  ADD CONSTRAINT loads_status_check
  CHECK (status IN ('open', 'assigned', 'in_transit', 'delivered', 'completed', 'cancelled'));

ALTER TABLE IF EXISTS public.notifications
  ADD COLUMN IF NOT EXISTS actor_id UUID;

UPDATE public.notifications
SET actor_id = user_id
WHERE actor_id IS NULL;

ALTER TABLE IF EXISTS public.notifications
  ALTER COLUMN actor_id SET DEFAULT auth.uid();

ALTER TABLE IF EXISTS public.notifications
  ALTER COLUMN actor_id SET NOT NULL;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_loads_employer_id ON public.loads(employer_id);
CREATE INDEX IF NOT EXISTS idx_loads_created_at ON public.loads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_loads_status ON public.loads(status);
CREATE INDEX IF NOT EXISTS idx_loads_status_created_at ON public.loads(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_loads_origin_destination ON public.loads(origin_city, destination_city);
CREATE INDEX IF NOT EXISTS idx_loads_active_created_at
  ON public.loads(created_at DESC)
  WHERE status IN ('open', 'assigned', 'in_transit', 'delivered');
CREATE INDEX IF NOT EXISTS idx_bids_load_id ON public.bids(load_id);
CREATE INDEX IF NOT EXISTS idx_bids_driver_id ON public.bids(driver_id);
CREATE INDEX IF NOT EXISTS idx_bids_load_status ON public.bids(load_id, status);
CREATE INDEX IF NOT EXISTS idx_bids_driver_status ON public.bids(driver_id, status);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_runtime_logs_created_at ON public.runtime_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_runtime_logs_level ON public.runtime_logs(level);
CREATE INDEX IF NOT EXISTS idx_runtime_logs_event_code ON public.runtime_logs(event_code);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_load_id ON public.abuse_reports(load_id);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_reporter_id ON public.abuse_reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_status_created ON public.abuse_reports(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_items_created_at ON public.feedback_items(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_items_status_tag ON public.feedback_items(status_tag);
CREATE INDEX IF NOT EXISTS idx_feedback_items_moderation ON public.feedback_items(moderation_status, created_at DESC);

DO $$
BEGIN
  ALTER TABLE public.notifications
    ADD CONSTRAINT notifications_actor_id_fkey
    FOREIGN KEY (actor_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

-- RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runtime_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.abuse_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback_items ENABLE ROW LEVEL SECURITY;

-- Drop old policies to keep this file re-runnable
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Public loads are viewable by everyone" ON public.loads;
DROP POLICY IF EXISTS "Employers can insert loads" ON public.loads;
DROP POLICY IF EXISTS "Employers can update own loads" ON public.loads;
DROP POLICY IF EXISTS "Employers can delete own loads" ON public.loads;
DROP POLICY IF EXISTS "Drivers can insert own bids" ON public.bids;
DROP POLICY IF EXISTS "Drivers can see own bids or bids on their loads" ON public.bids;
DROP POLICY IF EXISTS "Employers can respond bids on own loads" ON public.bids;
DROP POLICY IF EXISTS "Users can create notifications as themselves" ON public.notifications;
DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can delete own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Runtime logs are viewable by everyone" ON public.runtime_logs;
DROP POLICY IF EXISTS "Runtime logs can be inserted by everyone" ON public.runtime_logs;
DROP POLICY IF EXISTS "Users can insert own abuse reports" ON public.abuse_reports;
DROP POLICY IF EXISTS "Users can read own abuse reports" ON public.abuse_reports;
DROP POLICY IF EXISTS "Public feedback visible by everyone" ON public.feedback_items;
DROP POLICY IF EXISTS "Users can insert own feedback" ON public.feedback_items;

-- profiles
CREATE POLICY "Public profiles are viewable by everyone"
ON public.profiles
FOR SELECT
USING (true);

CREATE POLICY "Users can insert their own profile"
ON public.profiles
FOR INSERT
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- loads
CREATE POLICY "Public loads are viewable by everyone"
ON public.loads
FOR SELECT
USING (true);

CREATE POLICY "Employers can insert loads"
ON public.loads
FOR INSERT
WITH CHECK (auth.uid() = employer_id);

CREATE POLICY "Employers can update own loads"
ON public.loads
FOR UPDATE
USING (auth.uid() = employer_id)
WITH CHECK (auth.uid() = employer_id);

CREATE POLICY "Employers can delete own loads"
ON public.loads
FOR DELETE
USING (auth.uid() = employer_id);

-- bids
CREATE POLICY "Drivers can insert own bids"
ON public.bids
FOR INSERT
WITH CHECK (auth.uid() = driver_id);

CREATE POLICY "Drivers can see own bids or bids on their loads"
ON public.bids
FOR SELECT
USING (
  auth.uid() = driver_id OR
  EXISTS (
    SELECT 1
    FROM public.loads l
    WHERE l.id = bids.load_id
      AND l.employer_id = auth.uid()
  )
);

CREATE POLICY "Employers can respond bids on own loads"
ON public.bids
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.loads l
    WHERE l.id = bids.load_id
      AND l.employer_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.loads l
    WHERE l.id = bids.load_id
      AND l.employer_id = auth.uid()
  )
);

-- notifications
CREATE POLICY "Users can create notifications as themselves"
ON public.notifications
FOR INSERT
WITH CHECK (auth.uid() = actor_id);

CREATE POLICY "Users can read own notifications"
ON public.notifications
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update own notifications"
ON public.notifications
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own notifications"
ON public.notifications
FOR DELETE
USING (auth.uid() = user_id);

-- runtime_logs
CREATE POLICY "Runtime logs are viewable by everyone"
ON public.runtime_logs
FOR SELECT
USING (true);

CREATE POLICY "Runtime logs can be inserted by everyone"
ON public.runtime_logs
FOR INSERT
WITH CHECK (true);

-- abuse_reports
CREATE POLICY "Users can insert own abuse reports"
ON public.abuse_reports
FOR INSERT
WITH CHECK (auth.uid() = reporter_id);

CREATE POLICY "Users can read own abuse reports"
ON public.abuse_reports
FOR SELECT
USING (auth.uid() = reporter_id);

-- feedback_items
CREATE POLICY "Public feedback visible by everyone"
ON public.feedback_items
FOR SELECT
USING (true);

CREATE POLICY "Users can insert own feedback"
ON public.feedback_items
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- role data migration / cleanup for legacy rows
UPDATE public.profiles
SET role = 'driver'
WHERE role IS NULL
   OR role NOT IN ('driver', 'employer', 'admin');

-- Public stats fast path (count + distinct city count)
CREATE OR REPLACE FUNCTION public.get_public_stats_fast()
RETURNS TABLE(active_loads BIGINT, active_drivers BIGINT, active_cities BIGINT)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH active_load_rows AS (
    SELECT origin_city, destination_city
    FROM public.loads
    WHERE status NOT IN ('completed', 'cancelled')
  ),
  city_rows AS (
    SELECT origin_city AS city FROM active_load_rows WHERE origin_city IS NOT NULL
    UNION
    SELECT destination_city AS city FROM active_load_rows WHERE destination_city IS NOT NULL
  )
  SELECT
    (SELECT COUNT(*) FROM active_load_rows) AS active_loads,
    (SELECT COUNT(*) FROM public.profiles WHERE role = 'driver') AS active_drivers,
    (SELECT COUNT(*) FROM city_rows) AS active_cities;
$$;

REVOKE ALL ON FUNCTION public.get_public_stats_fast() FROM public;
GRANT EXECUTE ON FUNCTION public.get_public_stats_fast() TO anon, authenticated;

-- Deterministic load status transition helper
CREATE OR REPLACE FUNCTION public.set_load_status_with_transition(
  p_load_id BIGINT,
  p_next_status TEXT
)
RETURNS TABLE(id BIGINT, status TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_current TEXT;
  v_owner UUID;
BEGIN
  SELECT l.status, l.employer_id
  INTO v_current, v_owner
  FROM public.loads l
  WHERE l.id = p_load_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Load not found';
  END IF;

  IF auth.uid() IS DISTINCT FROM v_owner THEN
    RAISE EXCEPTION 'Unauthorized load status transition';
  END IF;

  IF p_next_status NOT IN ('open', 'assigned', 'in_transit', 'delivered', 'completed', 'cancelled') THEN
    RAISE EXCEPTION 'Unsupported target status: %', p_next_status;
  END IF;

  IF v_current = p_next_status THEN
    RETURN QUERY SELECT p_load_id, v_current;
    RETURN;
  END IF;

  IF NOT (
    (v_current = 'open' AND p_next_status IN ('assigned', 'cancelled')) OR
    (v_current = 'assigned' AND p_next_status IN ('in_transit', 'cancelled')) OR
    (v_current = 'in_transit' AND p_next_status IN ('delivered', 'cancelled')) OR
    (v_current = 'delivered' AND p_next_status IN ('completed')) OR
    (v_current = 'completed' AND p_next_status IN ('completed')) OR
    (v_current = 'cancelled' AND p_next_status IN ('cancelled'))
  ) THEN
    RAISE EXCEPTION 'Invalid transition: % -> %', v_current, p_next_status;
  END IF;

  UPDATE public.loads
  SET status = p_next_status
  WHERE public.loads.id = p_load_id;

  RETURN QUERY
  SELECT l.id, l.status
  FROM public.loads l
  WHERE l.id = p_load_id;
END;
$$;

REVOKE ALL ON FUNCTION public.set_load_status_with_transition(BIGINT, TEXT) FROM public;
GRANT EXECUTE ON FUNCTION public.set_load_status_with_transition(BIGINT, TEXT) TO authenticated;
