
-- USERS (Supabase Auth ile senkronize)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT CHECK (role IN ('driver', 'employer', 'admin')),
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- LOADS (Yük İlanları)
CREATE TABLE public.loads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id UUID REFERENCES public.profiles(id) NOT NULL,
  
  -- Konum Bilgileri
  origin_city TEXT NOT NULL,
  destination_city TEXT NOT NULL,
  distance_km INTEGER,
  
  -- Yük Detayları
  load_type TEXT NOT NULL, -- Ör: Tekstil, Gıda
  trailer_type TEXT CHECK (trailer_type IN ('Kapalı', 'Açık', 'Frigorifik', 'Damperli')),
  weight_kg INTEGER,
  price DECIMAL(10,2),
  currency TEXT DEFAULT 'TRY',
  
  -- Durum ve Tarih
  status TEXT CHECK (status IN ('open', 'assigned', 'completed', 'cancelled')) DEFAULT 'open',
  pickup_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Ek Özellikler
  is_urgent BOOLEAN DEFAULT FALSE,
  is_fleet BOOLEAN DEFAULT FALSE, -- Filo işi mi?
  truck_count INTEGER DEFAULT 1   -- Kaç araç lazım?
);

-- OFFERS (Teklifler)
CREATE TABLE public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id BIGINT REFERENCES public.loads(id) ON DELETE CASCADE NOT NULL,
  driver_id UUID REFERENCES public.profiles(id) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  status TEXT CHECK (status IN ('pending', 'accepted', 'rejected')) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) Politikaları
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

-- Herkes ilanları görebilir
CREATE POLICY "Public loads are viewable by everyone" ON public.loads FOR SELECT USING (true);

-- Sadece giriş yapmış kullanıcılar profil oluşturabilir
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Sadece işverenler ilan ekleyebilir
CREATE POLICY "Employers can insert loads" ON public.loads FOR INSERT WITH CHECK (auth.uid() = employer_id);
